### ISSUE TITLE
Lots and lots of errors

### ISSUE THREAD

**Issue by dandare76** [blocktrail/blocktrail-webwallet#27]
The installation instructions don't work. After struggling with them, got the following errors:

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at C:\Program Files\nodejs\node_modules\serve\lib\server.js:72:13
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at C:\Program Files\nodejs\node_modules\serve\bin\serve.js:91:9
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\Program Files\nodejs\node_modules\serve\node_modules\bluebird\js\release\generators.js:201:15
    at Promise.then (C:\Program Files\nodejs\node_modules\serve\node_modules\micro-compress\src\index.js:12:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by rubensayshi** [comment]
Probably nodeJS version related, which NodeJS version are you using?
