### ISSUE TITLE
BCC Web Production WebWallet is stuck on transition

### ISSUE THREAD

**Issue by oojr** [blocktrail/blocktrail-webwallet#53]
url: https://bcc-wallet.btc.com/#/wallet

```shell
libs.js:34 Error: Document update conflict
    at n._errorHandler (https://s.btc.com/bcc-wallet/v4-0-12/js/app.js:4:9076)
    at n._pollTransactionsCatchHandler (https://s.btc.com/bcc-wallet/v4-0-12/js/app.js:4:6670)
    at u (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:9548)
    at https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:9720
    at p.$eval (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:17112)
    at p.$digest (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:15621)
    at https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:17199
    at a (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:2:2744)
    at https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:2:4855
    at r (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:34:28547) undefined
e.(anonymous function) @ libs.js:34
libs.js:34 Error transitioning to app.wallet.summary from   Object Object Error: Document update conflict
    at n._errorHandler (https://s.btc.com/bcc-wallet/v4-0-12/js/app.js:4:9076)
    at n._pollTransactionsCatchHandler (https://s.btc.com/bcc-wallet/v4-0-12/js/app.js:4:6670)
    at u (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:9548)
    at https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:9720
    at p.$eval (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:17112)
    at p.$digest (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:15621)
    at https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:3:17199
    at a (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:2:2744)
    at https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:2:4855
    at r (https://s.btc.com/bcc-wallet/v4-0-12/js/libs.js:34:28547)
```

**Comment by oojr** [comment]
now you can switch to BCC from https://wallet.btc.com 😎
